///////////////////////////////////////////////////////////
//  IGameObject.as
//  Macromedia ActionScript Implementation of the Interface IGameObject
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2009 6:41:57 PM
//  Original author: Kurniawan Fitriadi
///////////////////////////////////////////////////////////

package com.quadtree
{
	import com.quadtree.CQuadTreeNode;
	import com.shade.geom.CPoint;
	import com.shade.geom.CRectangle;

	/**
	 * @author Kurniawan Fitriadi
	 * @version 1.0
	 * @created 11-Nov-2009 6:41:57 PM
	 */
	public interface IGameObject
	{
		function _getBoundRect(): CRectangle;

		/**
		 * 
		 * @param value
		 */
		 
		function _getObjectId() : int;
		 
		function get _container(): CQuadTreeNodeContainer;

		/**
		 * 
		 * @param value
		 */
		function set _container(value:CQuadTreeNodeContainer): void;

		/**
		 * 
		 * @param value
		 */
		function set _worldPosition(value:CPoint): void;

		function get _worldPosition(): CPoint; 
		
		//function _testFilter(subject:IGameObject, flag:int): Boolean; 
		function _queryCollisionFilter(subject:IGameObject, flag:int): Boolean; 		// filter for collision query
		function _queryRangeFilter(subject:IGameObject, flag:int): Boolean; 			// filter for range query
		
		
		function _onAddedToTree(): void;			// triggered when container of this object is added to tree
		
		function _onRemovedFromTree(): void;		// triggered when container of this object is removed from tree
		
	}//end IGameObject

}